extensions:
    pim-job-instance-demo-product-export-edit:
        module: pim/form/common/edit-form

    pim-job-instance-demo-product-export-edit-main-image:
        module: pim/form/common/main-image
        parent: pim-job-instance-demo-product-export-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ExportCSV.svg

    pim-job-instance-demo-product-export-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-job-instance-demo-product-export-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-job-instance-demo-product-export-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-demo-product-export-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    pim-job-instance-demo-product-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-demo-product-export-edit
        position: 1000

    pim-job-instance-demo-product-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-demo-product-export-edit
        targetZone: content
        position: 100

    pim-job-instance-demo-product-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-demo-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-demo-product-export-edit-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-demo-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 130
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-demo-product-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-demo-product-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-demo-product-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-demo-product-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pim-job-instance-demo-product-export-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-demo-product-export-edit-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-demo-product-export-edit-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-demo-product-export-edit
        targetZone: title
        position: 100

    pim-job-instance-demo-product-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-demo-product-export-edit
        targetZone: meta
        position: 100

    pim-job-instance-demo-product-export-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-job-instance-demo-product-export-edit
        targetZone: buttons
        position: 50

    pim-job-instance-demo-product-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: pim-job-instance-demo-product-export-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.export_profile
                subTitle: pim_menu.item.export_profile
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-demo-product-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-demo-product-export-edit
        targetZone: buttons
        position: 120

    pim-job-instance-demo-product-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: pim-job-instance-demo-product-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    pim-job-instance-demo-product-export-edit-state:
        module: pim/form/common/state
        parent: pim-job-instance-demo-product-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    pim-job-instance-demo-product-export-edit-content-data:
        module: pim/job/product/edit/content/data
        parent: pim-job-instance-demo-product-export-edit-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    pim-job-instance-demo-product-export-edit-content-default-attribute-filters:
        module: pim/job/product/edit/content/data/default-attribute-filters
        parent: pim-job-instance-demo-product-export-edit-content-data
        config:
            types: [pim_catalog_identifier]

    pim-job-instance-demo-product-export-edit-content-data-help:
        module: pim/job/common/edit/content/data/help
        parent: pim-job-instance-demo-product-export-edit-content-data

    pim-job-instance-demo-product-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: pim-job-instance-demo-product-export-edit

    pim-job-instance-demo-product-export-edit-content-data-add-filter:
        module: pim/job/product/edit/content/data/add-select/attribute
        parent: pim-job-instance-demo-product-export-edit-content-data
        targetZone: headings
        position: 90