services:
    bolgatty_connector.job.job_parameters.demo_product_update:
        class: 'BolgattyDemoBundle\JobParameters\DemoProductExport'
        arguments:
            - '@pim_catalog.repository.channel'
            - ['%bolgatty_connector.job.demo_product_update.name%']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
    
    bolgatty_connector.job.job_parameters.product_history_csv_export:
        class: 'BolgattyDemoBundle\JobParameters\ProductHistoryCsvExport'
        arguments:
            - '@pim_catalog.repository.channel'
            - ['%bolgatty_connector.job.product_history_csv_export.name%']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }