parameters:
    bolgatty_connector.processor.normalization.product.class: BolgattyDemoBundle\Connector\Processor\DemoProductProcessor
    bolgatty_connector.processor.normalization.product_model.class: BolgattyDemoBundle\Connector\Processor\DemoProductModelProcessor

services:  
    bolgatty_connector.processor.normalization.product:
        class: '%bolgatty_connector.processor.normalization.product.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.processor.bulk_media_fetcher'
            - '@pim_catalog.product_model.fill_missing_values'

    bolgatty_connector.processor.normalization.product_model:
        class: '%bolgatty_connector.processor.normalization.product_model.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product_model'
            - '@pim_catalog.repository.attribute'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_connector.processor.bulk_media_fetcher'
            - '@?pim_catalog.values_filler.entity_with_family_variant'
            - '@bolgattydemo.connector.service'