services:
    bolgatty_connector.writer.product_csv:
        class: 'BolgattyDemoBundle\Connector\Writer\BaseWriter'
        arguments:
            - '@pim_connector.factory.flat_item_buffer'
            - '@pim_connector.writer.file.product.flat_item_buffer_flusher'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.writer.file.media_exporter_path_generator'
            - '@pim_catalog.localization.localizer.converter'
            - ['pim_catalog_file', 'pim_catalog_image']
            - '@bolgattydemo.connector.service'
            - '@bolgatty_connector.processor.normalization.product'
            - 'en_US'